<?php
/**
 * Trial Coupons module — cart / checkout side.
 *
 * Applies the coupon's trial to subscription products in the cart,
 * validates that a subscription is present, and renders the trial info
 * in the cart totals. Also fixes the ungrammatical German price string
 * generated by the WooCommerce Subscriptions translation catalog.
 *
 * @package SubscriptionsToolkitForWC
 */

defined( 'ABSPATH' ) || exit;

class WCST_Trial_Coupons_Cart {

	public function init() {
		/*
		 * Primary defense: hook WCS's own trial getters. Whenever WCS asks
		 * a subscription product "what is your trial length / period?", we
		 * answer with the value from the currently applied trial coupon —
		 * regardless of whether the product's own meta happens to carry
		 * the trial or not. This is what makes the trial survive checkout
		 * retries after a failed / cancelled payment: WCS uses these
		 * filters both on the initial calculation and on every subsequent
		 * recurring-cart rebuild, so there is no "gap" where the trial
		 * could be lost.
		 */
		// Priority 999: we want the LAST word on the trial value, after any
		// WCS-internal filter that might otherwise reset it back to 0.
		add_filter( 'woocommerce_subscriptions_product_trial_length', [ $this, 'filter_trial_length' ], 999, 2 );
		add_filter( 'woocommerce_subscriptions_product_trial_period', [ $this, 'filter_trial_period' ], 999, 2 );

		/*
		 * Secondary defense: still write the trial onto cart-item product
		 * clones. Third-party code or older WCS paths may read the meta
		 * directly rather than going through the getter filters above.
		 */
		add_action( 'woocommerce_before_calculate_totals',     [ $this, 'apply_trial_to_subscriptions' ], 5, 1 );
		add_filter( 'woocommerce_get_cart_item_from_session',  [ $this, 'apply_trial_on_session_load' ], 20, 3 );
		add_action( 'woocommerce_cart_loaded_from_session',    [ $this, 'recalculate_after_session_load' ], 20 );

		add_filter( 'woocommerce_coupon_is_valid',             [ $this, 'validate_cart_has_subscription' ], 10, 2 );
		add_filter( 'woocommerce_coupon_error',                [ $this, 'custom_error_message' ], 10, 3 );
		add_filter( 'woocommerce_cart_totals_coupon_label',    [ $this, 'cart_coupon_label' ], 10, 2 );
		add_filter( 'woocommerce_coupon_discount_amount_html', [ $this, 'cart_discount_amount_html' ], 10, 2 );
		add_filter( 'woocommerce_subscriptions_product_price_string', [ $this, 'fix_german_price_string' ], 20, 3 );
	}

	/**
	 * Filter WCS's product trial-length getter. Returns the coupon's trial
	 * length when a trial coupon is currently applied and the product is a
	 * subscription in the current cart.
	 *
	 * @param int|string      $length
	 * @param WC_Product|null $product
	 * @return int|string
	 */
	public function filter_trial_length( $length, $product = null ) {
		if ( ! $this->should_override_trial_for( $product ) ) {
			return $length;
		}
		list( $coupon_length ) = $this->get_active_trial_from_session();
		if ( $coupon_length > 0 ) {
			$this->debug( 'filter_trial_length override: product=' . $product->get_id() . ' old=' . $length . ' new=' . $coupon_length );
			return $coupon_length;
		}
		return $length;
	}

	/**
	 * Filter WCS's product trial-period getter. Mirror of filter_trial_length.
	 *
	 * @param string          $period
	 * @param WC_Product|null $product
	 * @return string
	 */
	public function filter_trial_period( $period, $product = null ) {
		if ( ! $this->should_override_trial_for( $product ) ) {
			return $period;
		}
		list( , $coupon_period ) = $this->get_active_trial_from_session();
		if ( '' !== $coupon_period ) {
			return $coupon_period;
		}
		return $period;
	}

	/**
	 * Log a message via WooCommerce's logger, but only when either the
	 * global WCST_DEBUG constant is set to true or WP_DEBUG is on. Nothing
	 * is written otherwise, so the store's log directory stays quiet on
	 * production. Enable temporarily by adding `define( 'WCST_DEBUG', true );`
	 * to wp-config.php.
	 */
	private function debug( $message ) {
		if ( ! ( defined( 'WCST_DEBUG' ) && WCST_DEBUG ) && ! ( defined( 'WP_DEBUG' ) && WP_DEBUG ) ) {
			return;
		}
		if ( ! function_exists( 'wc_get_logger' ) ) {
			return;
		}
		wc_get_logger()->info( (string) $message, [ 'source' => 'wcst-trial-coupons' ] );
	}

	/**
	 * Decide whether to override the trial for the given product on the
	 * current request.
	 *
	 * We deliberately do NOT verify that the product is currently in the
	 * cart: WCS asks for trial length very early in the request lifecycle
	 * (during cart hydration itself), when neither WC()->cart nor the
	 * session snapshot are fully populated yet. That timing hole caused
	 * every previous "in-cart" guard to silently return false and the
	 * override to be skipped. The trial coupon can only be applied when a
	 * subscription is in the cart to begin with (see
	 * validate_cart_has_subscription()), so the mere presence of the
	 * coupon in the session is a sufficient signal.
	 */
	private function should_override_trial_for( $product ) {
		if ( ! $product instanceof WC_Product ) {
			return false;
		}
		// Don't tamper inside wp-admin except during front-end AJAX.
		if ( is_admin() && ! wp_doing_ajax() ) {
			return false;
		}
		if ( ! $this->is_subscription_product( $product ) ) {
			return false;
		}
		list( $length ) = $this->get_active_trial_from_session();
		return $length > 0;
	}

	/**
	 * Per-request memoized lookup of [ length, period ] for the trial
	 * coupon currently applied. Reads from WC()->cart first (in-memory,
	 * always current within a request) and falls back to the session
	 * store — either can lead the other depending on the request phase.
	 *
	 * The cache is only stored for a successful hit; an empty result is
	 * never cached so a later call in the same request can still find
	 * the coupon once cart / session hydration completes.
	 *
	 * @return array{0:int,1:string}
	 */
	private function get_active_trial_from_session() {
		static $cache = null;
		if ( is_array( $cache ) && $cache[0] > 0 ) {
			return $cache;
		}

		$applied = [];
		if ( WC()->cart instanceof WC_Cart ) {
			$applied = (array) WC()->cart->get_applied_coupons();
		}
		if ( empty( $applied ) && WC()->session instanceof WC_Session ) {
			$applied = (array) WC()->session->get( 'applied_coupons', [] );
		}
		if ( empty( $applied ) ) {
			return [ 0, '' ];
		}

		$found = $this->find_trial_from_codes( $applied );
		if ( $found[0] > 0 ) {
			$cache = $found;
		}
		return $found;
	}

	/**
	 * Iterate every applied coupon; for each subscription_trial coupon,
	 * copy its trial length + period onto every subscription product in
	 * the cart. WooCommerce Subscriptions then treats those products as
	 * being on trial: total drops to 0.00 and the first renewal is
	 * scheduled after the trial ends.
	 *
	 * Called on woocommerce_before_calculate_totals — the cart's product
	 * objects are session-scoped clones, so modifying meta on them does
	 * NOT persist to the actual product post.
	 */
	public function apply_trial_to_subscriptions( $cart ) {
		if ( ! $cart instanceof WC_Cart ) {
			return;
		}
		$applied = $cart->get_applied_coupons();
		if ( empty( $applied ) ) {
			return;
		}

		list( $trial_length, $trial_period ) = $this->find_trial_from_codes( $applied );
		if ( $trial_length <= 0 || '' === $trial_period ) {
			return;
		}

		foreach ( $cart->cart_contents as $cart_item ) {
			if ( empty( $cart_item['data'] ) ) {
				continue;
			}
			$this->apply_trial_to_product( $cart_item['data'], $trial_length, $trial_period );
		}
	}

	/**
	 * Runs for every cart item as WooCommerce rebuilds the cart from session
	 * (on every request). The applied coupons are read directly from the
	 * session because at this point WC()->cart is not fully populated yet.
	 *
	 * Without this the order-review section of the checkout page — which is
	 * rendered before woocommerce_before_calculate_totals fires in some
	 * flows, notably after a failed payment attempt — would show the full
	 * price and no trial, even though the coupon still appears in the totals.
	 */
	public function apply_trial_on_session_load( $cart_item, $values, $key ) {
		$applied = ( WC()->session instanceof WC_Session )
			? (array) WC()->session->get( 'applied_coupons', [] )
			: [];
		if ( empty( $applied ) ) {
			return $cart_item;
		}
		list( $trial_length, $trial_period ) = $this->find_trial_from_codes( $applied );
		if ( $trial_length <= 0 || '' === $trial_period ) {
			return $cart_item;
		}

		if ( ! empty( $cart_item['data'] ) ) {
			$this->apply_trial_to_product( $cart_item['data'], $trial_length, $trial_period );
		}
		return $cart_item;
	}

	/**
	 * After session load, trigger a totals recalculation so WooCommerce
	 * Subscriptions rebuilds the recurring cart with the trial we just
	 * injected. Guarded to only fire when a trial coupon is actually
	 * applied so we don't slow down every request.
	 */
	public function recalculate_after_session_load( $cart ) {
		if ( ! $cart instanceof WC_Cart ) {
			return;
		}
		$applied = $cart->get_applied_coupons();
		if ( empty( $applied ) ) {
			return;
		}
		list( $length, $period ) = $this->find_trial_from_codes( $applied );
		if ( $length > 0 && '' !== $period ) {
			$cart->calculate_totals();
		}
	}

	/**
	 * Scan a list of coupon codes; return [ length, period ] of the last
	 * subscription_trial coupon found (later ones win — typical stores
	 * only allow one anyway). Falls back to reading meta directly when
	 * the discount_type check fails, because on checkout retry WCS can
	 * rehydrate a coupon whose type is not yet initialised.
	 *
	 * @return array{0:int,1:string}
	 */
	private function find_trial_from_codes( array $codes ) {
		$trial_length = 0;
		$trial_period = '';

		foreach ( $codes as $code ) {
			$coupon = new WC_Coupon( $code );
			$is_trial = $coupon->is_type( WCST_TRIAL_COUPON_TYPE );

			$length = (int) $coupon->get_meta( WCST_TRIAL_META_LENGTH );
			$period = (string) $coupon->get_meta( WCST_TRIAL_META_PERIOD );

			// If discount_type check missed but our meta is set, still treat
			// it as a trial coupon.
			if ( ! $is_trial && $length <= 0 ) {
				continue;
			}
			if ( $length > 0 && '' !== $period ) {
				$trial_length = $length;
				$trial_period = $period;
			}
		}

		return [ $trial_length, $trial_period ];
	}

	private function apply_trial_to_product( $product, $length, $period ) {
		if ( ! $this->is_subscription_product( $product ) ) {
			return;
		}
		$product->update_meta_data( '_subscription_trial_length', $length );
		$product->update_meta_data( '_subscription_trial_period', $period );
	}

	/**
	 * Reject the coupon at apply-time if the cart contains no subscription.
	 */
	public function validate_cart_has_subscription( $valid, $coupon ) {
		if ( ! $coupon instanceof WC_Coupon || ! $coupon->is_type( WCST_TRIAL_COUPON_TYPE ) ) {
			return $valid;
		}
		if ( ! WC()->cart ) {
			return $valid;
		}

		foreach ( WC()->cart->get_cart() as $item ) {
			if ( ! empty( $item['data'] ) && $this->is_subscription_product( $item['data'] ) ) {
				return $valid;
			}
		}

		$coupon->error_code = 'wcst_no_subscription_in_cart';
		return false;
	}

	public function custom_error_message( $err, $err_code, $coupon ) {
		if ( isset( $coupon->error_code ) && 'wcst_no_subscription_in_cart' === $coupon->error_code ) {
			return __( 'This coupon can only be applied when the cart contains a subscription product.', 'wc-subs-toolkit' );
		}
		return $err;
	}

	/**
	 * Label shown in the cart / checkout totals for the applied coupon.
	 */
	public function cart_coupon_label( $label, $coupon ) {
		if ( $coupon instanceof WC_Coupon && $coupon->is_type( WCST_TRIAL_COUPON_TYPE ) ) {
			return esc_html__( 'Free trial', 'wc-subs-toolkit' ) . ' (' . esc_html( strtoupper( $coupon->get_code() ) ) . ')';
		}
		return $label;
	}

	/**
	 * Show "10 days" instead of a monetary discount next to the coupon
	 * in the cart totals — the actual price change happens because the
	 * subscription trial makes the initial total 0.00.
	 */
	public function cart_discount_amount_html( $discount_html, $coupon ) {
		if ( ! $coupon instanceof WC_Coupon || ! $coupon->is_type( WCST_TRIAL_COUPON_TYPE ) ) {
			return $discount_html;
		}
		$length = (int) $coupon->get_meta( WCST_TRIAL_META_LENGTH );
		$period = (string) $coupon->get_meta( WCST_TRIAL_META_PERIOD );

		if ( $length <= 0 || '' === $period ) {
			return esc_html__( 'Free trial period', 'wc-subs-toolkit' );
		}

		return esc_html( $this->format_trial_period( $length, $period ) );
	}

	private function is_subscription_product( $product ) {
		if ( ! $product instanceof WC_Product ) {
			return false;
		}
		if ( class_exists( 'WC_Subscriptions_Product' ) ) {
			if ( WC_Subscriptions_Product::is_subscription( $product ) ) {
				return true;
			}
		}
		return $product->is_type( 'subscription' ) || $product->is_type( 'subscription_variation' );
	}

	/**
	 * Return a translated, pluralized period string like "15 days" / "1 month".
	 *
	 * We intentionally do NOT reuse wcs_get_subscription_period_strings():
	 * the German WooCommerce Subscriptions catalog translates the plural
	 * templates without the "%s " placeholder ("Tage" instead of "%s Tage"),
	 * which produced "Tag" in the cart totals with no number. Formatting
	 * with our own text domain avoids that gotcha and lets us ship the
	 * translations bundled with this plugin.
	 */
	private function format_trial_period( $length, $period ) {
		switch ( $period ) {
			case 'day':
				/* translators: %d: number of days */
				return sprintf( _n( '%d day', '%d days', $length, 'wc-subs-toolkit' ), $length );
			case 'week':
				/* translators: %d: number of weeks */
				return sprintf( _n( '%d week', '%d weeks', $length, 'wc-subs-toolkit' ), $length );
			case 'month':
				/* translators: %d: number of months */
				return sprintf( _n( '%d month', '%d months', $length, 'wc-subs-toolkit' ), $length );
			case 'year':
				/* translators: %d: number of years */
				return sprintf( _n( '%d year', '%d years', $length, 'wc-subs-toolkit' ), $length );
			default:
				return $length . ' ' . $period;
		}
	}

	/**
	 * WooCommerce Subscriptions' German translation renders the trial phrase
	 * as "mit ein 15-Tage kostenlose Testphase", which is grammatically
	 * broken (wrong article gender, wrong case ending). Rewrite it to the
	 * correct dative form: "mit 15 Tagen kostenloser Testphase".
	 *
	 * Applied only for German locales so English and other languages are
	 * untouched.
	 */
	public function fix_german_price_string( $string, $product = null, $include = null ) {
		if ( ! is_string( $string ) || '' === $string ) {
			return $string;
		}
		$locale = function_exists( 'determine_locale' ) ? determine_locale() : get_locale();
		if ( 0 !== strpos( (string) $locale, 'de' ) ) {
			return $string;
		}

		return preg_replace_callback(
			'/mit\s+ein\s+(\d+)-(Tag|Tage|Woche|Wochen|Monat|Monate|Jahr|Jahre)\s+kostenlose[nrs]?\s+Testphase/u',
			static function ( $m ) {
				$dative_plural = [
					'Tag'    => 'Tag',    'Tage'   => 'Tagen',
					'Woche'  => 'Woche',  'Wochen' => 'Wochen',
					'Monat'  => 'Monat',  'Monate' => 'Monaten',
					'Jahr'   => 'Jahr',   'Jahre'  => 'Jahren',
				];
				$unit = $dative_plural[ $m[2] ] ?? $m[2];
				return 'mit ' . (int) $m[1] . ' ' . $unit . ' kostenloser Testphase';
			},
			$string
		);
	}
}
